### ISSUE TITLE
For wr.s3.select_query on a parquet file, can it convert int96 to timestamp

### ISSUE THREAD

**Issue by mandywoo** [awslabs/aws-data-wrangler#1060]
I'm using wr.s3.select_query to query from a parquet file that has timestamp data that has been converted to a int96 type. What I get back is a dataframe with the int96 type. However, when I use wr.s3.read_parquet, I would get back a dataframe with the timestamp in a timestamp format instead of int96. Is there anyway to get timestamp data in a timestamp format when using wr.s3.select_query.

**Comment by jaidisido** [comment]
Because the `read_parquet` method interacts with the Glue catalog, we are enforcing Athena data types on the pandas data frame. As a result int96 type is converted to timestamp. `select_query` does not leverage the Glue catalog and a conversion is not required. It's up to the user to convert it if need be.
