### ISSUE TITLE
awswrangler.redshift.connect fails with interface/communication error  in glue pyspark job

### ISSUE THREAD

**Issue by venke2191** [awslabs/aws-data-wrangler#1083]
I'm storing Redshift credentials in secret manager. When I'm trying to connect to Redshift using the secret from Glue Pyspark Job (Glue version 3.0, Language: Python)
conn=wr.redshift.connect(secret_id='<secret name>')
It fails with below error:

2021-12-22 11:37:16,443 ERROR [main] glue.ProcessLauncher (Logging.scala:logError(73)): Error from Python:Traceback (most recent call last):
  File "/tmp/awswrangler-layer-2.13.0-py3.7-updated.zip/redshift_connector/core.py", line 559, in __init__
    ssl_context.load_verify_locations(path)
NotADirectoryError: [Errno 20] Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/aws_wrangler_test.py", line 33, in <module>
    region='eu-west-1')
  File "/tmp/awswrangler-layer-2.13.0-py3.7-updated.zip/redshift_connector/__init__.py", line 352, in connect
    credentials_provider=info.credentials_provider,
  File "/tmp/awswrangler-layer-2.13.0-py3.7-updated.zip/redshift_connector/core.py", line 585, in __init__
    raise InterfaceError("communication error", e)
redshift_connector.error.InterfaceError: ('communication error', NotADirectoryError(20, 'Not a directory'))

P.S: Same command works fine in Lambda.

**Comment by jaidisido** [comment]
It seems to fail when attempting to use a certificate to establish an ssl connection. Is there anything about your Glue job setup that would explain this difference when compared to a Lambda? Perhaps it's behind a VPC or something else?

@Brooke-white would you have an idea of what could be causing the issue here please?

**Comment by venke2191** [comment]
I have created a glue connection for Redshift with same VPC, subnet, security group configured for Lambda function. Test connection succeeded. I'm able to connect to Redshift using spark read/write methods, glue dynamic frame read/write methods and also using pg8000 library in my Glue pyspark job. So clearly there is no issue with security group. Connection fails only when using awswrangler.redshift.connect method using secret. Please help.

**Comment by venke2191** [comment]
You are right about the ssl part. Connection is successful when ssl is set to False.
 conn=wr.redshift.connect(secret_id='<SECRETID>', ssl=False)

But I would like to know why it fails when ssl is set to True and how to resolve it. Please help.

**Comment by Brooke-white** [comment]
Hi @venke2191 , I'm taking a look into this.

**Comment by kukushking** [comment]
My 2 cents - it looks like redshift connector is trying to load certificates from a directory that doesn't exist in Glue pyspark environment:
```
ssl_context.load_verify_locations(path)
NotADirectoryError: [Errno 20] Not a directory
```
I recall there was somewhat similar [issue](https://github.com/awslabs/aws-data-wrangler/pull/664/files) with MySQL connections. Ultimate solution would be for wrangler to create SSL context and be able to pass it over to redshift connector. The connector would also have to accept `ssl_context` parameter to be able to do so.

However, I can see `ssl_context.load_default_certs()` [was added](https://github.com/aws/amazon-redshift-python-driver/commit/122292a23b5fd4ca11547086dfd74fbf2149af4d) to the connector so perhaps if the CA certificate is in the default trust store that could be enough. My only worry is that `ssl_context.load_verify_locations(path)` call after still might fail because of the unknown path.
