### ISSUE TITLE
Suggestion: remove boto3 and botocore from lambda layer

### ISSUE THREAD

**Issue by vfilimonov** [awslabs/aws-data-wrangler#113]
It might be a good idea to remove `boto3` and `botocore` from the lambda layer - anyway they are provided at lambda and it will decrease layer's weight by ~15%. 

`botocore` is 43 MB out of 220 MB unzipped (10 MB out of 60 MB zipped).

5 largest contributors to the package:
```
3.6M	./docutils
 29M	./pandas
 43M	./botocore
 63M	./pyarrow
 72M	./numpy
```

**Comment by igorborgest** [comment]
Make total sense for me. Next release will not have Boto3 embedded on Layer anymore.

@vfilimonov thank you for this and all others valuable issues that you've opened. Working to address all of them.

**Comment by igorborgest** [comment]
Done for version [0.2.6](https://github.com/awslabs/aws-data-wrangler/releases/tag/0.2.6) and beyond! 🚀 

P.S. Please, keep giving feedbacks!

**Comment by jaidisido** [comment]
Great stuff, @igorborgest does that mean that we can install this layer version in sdlf through a pip install instead of a zip?

**Comment by igorborgest** [comment]
@jaidisido not really, because the *pip install* still installing the whole PyArrow package that does not fit into a Lambda Layer. We still need to use the zip files that are [created removing some unnecessary modules](https://github.com/awslabs/aws-data-wrangler/blob/master/building/build-pyarrow.sh).

The good news is that now it is easer because our layers have less than 50MB and can be uploaded directly w/o staging on S3.

```py3
from urllib.request import urlopen
import boto3

URL = "https://github.com/awslabs/aws-data-wrangler/releases/download/0.2.6/awswrangler-layer-0.2.6-py3.7.zip"

boto3.client("lambda").publish_layer_version(
    LayerName="aws-data-wrangler",
    Content={"ZipFile": urlopen(URL).read()},
    CompatibleRuntimes=["python3.7"],
)
```
