### ISSUE TITLE
Error when using a athena database name having a dash '-' 

### ISSUE THREAD

**Issue by sujayramaiah** [awslabs/aws-data-wrangler#118]
I am trying to execute an ALTER TABLE command and and when dbname has a '-' in it. The query errors.

db_name = 'glue-athena'
wr.athena.query(query = sql, database = db_name)

Below is the exception:
<class 'awswrangler.exceptions.QueryFailed'>, QueryFailed("FAILED: ParseException line 1:8 missing EOF at '-' near 'glue'",)

**Comment by igorborgest** [comment]
Hi @sujayramaiah, thank you very much for this issue. It always help us to evolve the library.

Did you have tried this same query into the AWS Athena console?

Because I don't think that it is an issue with Wrangler it self. I've executed some tests here and I'm able to query against databases with "-" like a charm.

Seems to me that you probably are forgetting to quote the database name in your query.

E.g.

```py3
import awswrangler as wr

rows = wr.athena.query(query="SHOW TABLES IN `foo-boo`", database="foo-boo")

print(list(rows))
```

**Comment by igorborgest** [comment]
Closing by inactivity...

**Comment by dror-g** [comment]
@igorborgest I'm getting the same error when using the Athena web console, no Wrangler involved.
(clicking on 3 dots near table name -> Load partitions).

**Comment by patrick-muller** [comment]
Hi @dror-g,
The reason for the error is because Athena doesn't support dash in the table names.

https://docs.aws.amazon.com/athena/latest/ug/glue-best-practices.html#schema-names

# The only acceptable characters for database names, table names, and column names are lowercase letters, numbers, and the underscore character.

I am going to add it in our documentation as well
