### ISSUE TITLE
athena.read_sql_query() casting to pandas ExtensionDtypes only

### ISSUE THREAD

**Issue by koberghe** [awslabs/aws-data-wrangler#1265]
Data types are converted to pandas Extension Dtypes when calling athena.read_sql_query(). Is there a way to prevent this and get basic numpy dtypes instead of nullable pandas dytpes? (e.g. `int64` instead of `Int64`). This would be useful, for example when the data is further processed with numpy.

I believe this conversion is happening in [athena2pandas](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/_data_types.py#L301)

A similar issue was raised for [to_parquet](https://github.com/awslabs/aws-data-wrangler/issues/580) some time ago for which the parameter `map_types` was introduced.

**Comment by jaidisido** [comment]
Hi @koberghe, pandas extension dtypes are used to avoid situations where, for example, an integer column in Athena has null values and a conversion to `int64` in pandas would convert the column to a float instead of an integer. See here for more [details](https://pandas.pydata.org/docs/user_guide/integer_na.html). A user can always convert to int64 if they wish, but at the same time I do appreciate that we are already allowing that behaviour in `to_parquet` at the moment

**Comment by koberghe** [comment]
Hi @jaidisido! Thank you for your explanation. Extension dtypes are useful without doubt. It just came as a surprise to me when the outpout of athena.read_sql_query used them by default. To my knowledge, `pd.read_csv` and `pd.read_parquet` both use standard integers unless specified otherwise. I guess this can be expected given the experimental status described in the link you provided.

But agreed, casting to int64 is of course a solution. And that is what I am doing. :-)
