### ISSUE TITLE
fast_executemany for sqlserver

### ISSUE THREAD

**Issue by robert-schmidtke** [awslabs/aws-data-wrangler#1293]
Hi, I was wondering whether you're not setting `fast_executemany = True` in `sqlserver`, e.g. here: https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/sqlserver.py#L411

Wouldn't that make sense, especially for large number of rows? Or am I completely on the wrong track here?

Thanks!

**Comment by kukushking** [comment]
Hi @robert-schmidtke thanks, it does make sense to at least expose a parameter to enable/disable it. In `pyodbc`, it is `False` by default due to the fact that there are slight differences in data types conversions with and without fast_executemany. We'll add it or happy to accept a contribution as well 🙂

**Comment by robert-schmidtke** [comment]
Hey @kukushking thanks for coming back to me on this! I am not sure when I'll be able to address this, so if you have a schedule on your own it'd be great if you could also add it. Otherwise I'll try and get a PR together maybe some time this week.

**Comment by robert-schmidtke** [comment]
Thanks that was fast <3
