### ISSUE TITLE
Unable to use a schema with a -

### ISSUE THREAD

**Issue by AlistairDow** [awslabs/aws-data-wrangler#1352]
### Describe the bug

The bug occurs when calling a schema with a - (minus symbol) in it

{'S': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "-"', 'P': '20', 'F': '/home/ec2-user/padb/src/pg/src/backend/parser/parser_scan.l', 'L': '714', 'R': 'yyerror'}

This has been run and tested in a lambda function

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

  wr.redshift.to_sql(
            df=df,
            table="table_name",
            schema="redshift-schema",
            mode="upsert",
            con=con,
            dtype=dtype_dict,
            use_column_names = True,
            lock = True
            primary_keys = ["pk1","pk2"]
        )

This causes the error to occur wheras "redshift_schema" didn't.

I attempted a workaround using '"redshift-schema"' but this caused another error.

### OS

Linux

### Python version

3.8

### AWS DataWrangler version

2.14

**Comment by maxdavidson91** [comment]
To replicate this issue, you would have to use the `wr.redshift.to_sql` method with `mode` set to "upsert" and a `schema` that contains a hyphen (`-`)

I haven't tested this myself, but it appears the issue is due to `{schema}` and `{table}` not being wrapped in double quotes like they are elsewhere.

Example:
`insert_sql = f"INSERT INTO {schema}.{table} SELECT * FROM {temp_table}"` 

This is the code that I believe is causing the issue: [source code](https://github.com/awslabs/aws-data-wrangler/blob/main/awswrangler/redshift.py#:~:text=insert_sql%20%3D%20f%22INSERT%20INTO%20%7B,SELECT%20*%20FROM%20%7Btemp_table%7D%22)
