### ISSUE TITLE
Consistent Lambda Layers versions across regions

### ISSUE THREAD

**Issue by vgkowski** [awslabs/aws-data-wrangler#1358]
**Is your idea related to a problem? Please describe.**
Currently, the lambda layers versions (the latest digit in the layer ARN) are not the same for each region:

`arn:aws:lambda:eu-west-1:336392948345:layer:AWSDataWrangler-Python39:5` for eu-west-1
`arn:aws:lambda:eu-west-2:336392948345:layer:AWSDataWrangler-Python39:3` for eu-west-2

Additionally, some versions are not available in all the regions: 
`arn:aws:lambda:ca-central-1:336392948345:layer:AWSDataWrangler-Python39:3` is the latest in ca-central-1 
but `arn:aws:lambda:us-east-1:336392948345:layer:AWSDataWrangler-Python39:3` is not available in us-east-1.

At the end it's not possible to implement a CDK stack relying on Data Wrangler layer and make it deployable in multiple regions.

**Describe the solution you'd like**
Consistent version numbers in all the regions where the Lambda Layer is available

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*

**Comment by vgkowski** [comment]
In that case why are there gaps in the versioning? For example in eu-west-1, we have:

`arn:aws:lambda:eu-west-1:336392948345:layer:AWSDataWrangler-Python38:7`
and `arn:aws:lambda:eu-west-1:336392948345:layer:AWSDataWrangler-Python38:4``

but no `arn:aws:lambda:eu-west-1:336392948345:layer:AWSDataWrangler-Python38:6`
no `arn:aws:lambda:eu-west-1:336392948345:layer:AWSDataWrangler-Python38:5`

**Comment by malachi-constant** [comment]
Hi @vgkowski, unfortunately due to how we manage these layers there was incident where layers had to be recreated (deleting current version and creating a new and incremented version). This should not happen in the future as we continue to increment. 

Take a look at our [Serverless Applicaction Repository (SAR) apps](https://aws-data-wrangler.readthedocs.io/en/stable/install.html?highlight=sar#serverless-application-repository-sar) as well, as they are pinned explicitly to their wrangler semantic version which may be a better experience for you.
