### ISSUE TITLE
relationship to pandasglue? and multithreading error in AWS Lambda

### ISSUE THREAD

**Issue by mjh7** [awslabs/aws-data-wrangler#14]
Hi there, I'm getting started with AWS preparing to implement Data Lake. Thanks for creating these packages! I currently have pandasglue stack installed in an AWS Lambda Layer with intent of lightweight ETL and I'm running some "hello world" type lambda functions to test. I'm wondering if the scope of aws-data-wrangler project covers that of pandasglue, or if there are different use cases for that? Maybe I should be using aws-data-wrangler instead? (I didn't see a link to post an issue on the pandasglue github page.)

So far, I was able to read-in an existing glue table to a pandas dataframe, but when trying to write I get an error that might be related to multithreading (s3.py calls mp.Pool). Here are a couple quotes from other posts I found when googling around:

> Python's _multithreading requires /dev/shm to work.

> AWS Lambda execution environment does not have /dev/shm (shared memory for processes) support.

My lambda function:

`

    import pandas as pd
    import pandasglue as pg

    def lambda_handler(event, context):
    
        #Parameters
        database = "glue-test-db"
        table_name = "pg-test"
        s3_path = "s3://nonlake-test-bucket/pg-test"
        
        #Sample DF
        source_data = {'name': ['Sarah', 'Renata', 'Erika', 'Fernanda', 'Diana'], 
                'city': ['Seattle', 'Sao Paulo', 'Seattle', 'Santiago', 'Lima'],
                 'test_score': [82, 52, 56, 234, 254]}
        
        df = pd.DataFrame(source_data, columns = ['name', 'city', 'test_score'])
        
        pg.write_glue(df, database, s3_path, table_name, partition_cols=['city'], mode="overwrite")
`

output:

[ERROR] OSError: [Errno 38] Function not implemented
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 18, in lambda_handler
    pg.write_glue(df, database, s3_path, table_name, partition_cols=['city'], mode="overwrite")
  File "/opt/python/lib/python3.7/site-packages/pandasglue/__init__.py", line 25, in write_glue
    return write.write(**locals())
  File "/opt/python/lib/python3.7/site-packages/pandasglue/write.py", line 124, in write
    s3.delete_objects(path, session_primitives=session_primitives)
  File "/opt/python/lib/python3.7/site-packages/pandasglue/services/s3.py", line 22, in delete_objects
    pool = mp.Pool(mp.cpu_count())
  File "/var/lang/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/var/lang/lib/python3.7/multiprocessing/pool.py", line 158, in __init__
    self._setup_queues()
  File "/var/lang/lib/python3.7/multiprocessing/pool.py", line 251, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/var/lang/lib/python3.7/multiprocessing/context.py", line 112, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/var/lang/lib/python3.7/multiprocessing/queues.py", line 332, in __init__
    self._rlock = ctx.Lock()
  File "/var/lang/lib/python3.7/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/var/lang/lib/python3.7/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)

**Comment by igorborgest** [comment]
Hi @mjh7, welcome to our community!

#### I little bit about **awswrangler** and **pandasglue** history:

We have coded pandasglue only for a proof of concept purpose in a private GitHub account.
After the validation of the idea, we started awswrangler, a new (*and seriously*) project here in the awslabs account.
AWS Data Wrangler (awswrangler) is thousand times faster and more stable than pandasglue and also has a lot of more features.
So, **you absolutely should go with AWS Data Wrangler!**

P.S. I will update pandasglue ASAP to make explicit the deprecation.

#### About the bug that you are facing:

That's true, Lambda environment has limitations related to multithreading and shared memory in general. The good news is that this already was addressed on AWS Data Wrangler, and we are now supporting lambdas running on Python3.6 and Python3.7.
Behind the scenes we are using a processes (*multiprocessing*) to parallelize everything. This is awesome because works on lambda and also allows performance improvements.

#### About your code:

Everything is great here, you only need to adapt that to use AWS Data Wrangler instead pandasglue.
Actually I've already did that and are working like a charm:

```py3
import pandas as pd
import awswrangler

def lambda_handler(event, context):

    #Parameters
    database = "glue-test-db"
    table_name = "pg-test"
    s3_path = "s3://nonlake-test-bucket/pg-test"
    
    #Sample DF
    source_data = {'name': ['Sarah', 'Renata', 'Erika', 'Fernanda', 'Diana'], 
            'city': ['Seattle', 'Sao Paulo', 'Seattle', 'Santiago', 'Lima'],
             'test_score': [82, 52, 56, 234, 254]}
    
    df = pd.DataFrame(source_data, columns = ['name', 'city', 'test_score'])
    
    session = awswrangler.Session()
    session.pandas.to_parquet(
            dataframe=df,
            database=database,
            table=table_name,
            path=s3_path,
            preserve_index=False,
            mode="overwrite",
            partition_cols=['city'],
            procs_cpu_bound=4,
        )

```

#### About your environment:

The best way to use lambda dependencies (included the awswrangler library) is with [Lambda layers](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html).
I it is pretty easy with awswrangler, you only need to download the layer ZIP file in our [releases page ](https://github.com/awslabs/aws-data-wrangler/releases/tag/0.0b31)and create a layer on you AWS account and put as a dependency in you lambda.

P.S. AWS Data Wrangler layer already have Pandas, Numpy, PG8000 and others useful libraries.

#### General comments:

Please, let me know if you have other questions or difficulties using our library.

**Comment by mjh7** [comment]
Thanks for the confirmation - I was able to use the aws-data-wrangler pre-packaged Lambda Layer and write to a new glue table with partitioned parquet files showing up in s3  as desired. I will still have to get familiar with the tools, but this is a good start!
