### ISSUE TITLE
Support for Athena Iceberg tables

### ISSUE THREAD

**Issue by jaidisido** [awslabs/aws-data-wrangler#1400]
### Discussed in https://github.com/awslabs/aws-data-wrangler/discussions/1399

<div type='discussions-op-text'>

<sup>Originally posted by **andyadamides** June 17, 2022</sup>
Hi, based on the latest version of AWS Data Wrangler, I cannot see any support for Athena [Iceberg](https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg-creating-tables.html) tables. Is this on the roadmap?

</div>

**Comment by jaidisido** [comment]
@andyadamides I had a quick look at this and I am afraid it does not look possible. Athena is not exposing the [API calls](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena.html#client) required to replicate what their Iceberg engine is doing as I assume they handle everything internally.

So the only interaction that `awswrangler` can have with Iceberg tables is via the [Athena](https://aws-data-wrangler.readthedocs.io/en/stable/api.html#amazon-athena) methods. We might revisit this subject this feature if they were to expose their API calls.

**Comment by AdrianoNicolucci** [comment]
@jaidisido What about through the aws glue catalog instead of going through AWS Athena in order to read iceberg datasets? AWS has developed an Iceberg connector for aws glue: https://aws.amazon.com/marketplace/pp/prodview-iicxofvpqvsio and I believe we can have iceberg tables in the aws glue catalog.

I feel there is a huge opportunity where people want to interact with iceberg tables in aws but don't need to use a distributed cluster to do this.
