### ISSUE TITLE
UndetectedType: We can not infer the data type from an entire null object column

### ISSUE THREAD

**Issue by jadayn** [awslabs/aws-data-wrangler#218]
Unload from Aurora mysql and load into redshift. We are hitting the following error for one of the tables
**UndetectedType: We can not infer the data type from an entire null object column**

#unload from mysql
df = wr.db.read_sql_query("SELECT * FROM " + rds_schema + "." + table + " limit 5", con=eng_mysql)

#load to Redshift
wr.db.to_sql(df, eng_redshift, schema=rs_schema, name=table.lower(), if_exists="append", index=False)

The complete error stack is provided below.
[ERROR] UndetectedType: We can not infer the data type from an entire null object column
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 39, in lambda_handler
    wr.db.to_sql(df, eng_redshift, schema=rs_schema, name=table.lower(), if_exists="append", index=False)
  File "/opt/python/awswrangler/db.py", line 90, in to_sql
    df=df, db_type=con.name, dtype=cast_columns
  File "/opt/python/awswrangler/_data_types.py", line 384, in sqlalchemy_types_from_pandas
    sqlalchemy_columns_types[k] = pyarrow2sqlalchemy(dtype=v, db_type=db_type)
  File "/opt/python/awswrangler/_data_types.py", line 217, in pyarrow2sqlalchemy
    raise exceptions.UndetectedType("We can not infer the data type from an entire null object column")

**Comment by igorborgest** [comment]
Hi @jadayn, thanks for report it!

I just added support for read `null` columns from PostgreSQL, MySQL, and Redshift and it will be available in the next release `1.1.0`.

**Comment by igorborgest** [comment]
Available on version [1.1.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.1.0)

**Comment by husainzl** [comment]
Hello @igorborgest , I am having this issue when pulling data from BigQuery. Below is the error I get anytime someone adds a new null column on a source table. I am getting around this issue by passing in the dtype parameter but this is not a scalable solution because I will have to make a code change and release to prod anytime anyone adds new columns to any table on the source. Is there a fix in place for BigQuery? Thanks in advance for your help.

awswrangler.exceptions.UndetectedType: Impossible to infer the equivalent Athena data type for the language_code column. It is completely empty (only null values) and has a too generic data type (object). Please, cast this columns with a more deterministic data type (e.g. df['language_code'] = df['language_code'].astype('string')) or pass the column schema as argument for AWS Data Wrangler (e.g. dtype={'language_code': 'string'}

**Comment by rssanjeev** [comment]
Hi @igorborgest,

"**awswrangler.exceptions.UndetectedType: We can not infer the data type from an entire null object column**" 

Got this error while trying to write data into Redshift. 

Code:
    wr.redshift.copy(df,
                    path= 's3://.../',
                    table= 'abc',
                    schema= 'xyz',
                    iam_role= 'aws_role',
                    con= conn,
                    mode= 'overwrite',
                    overwrite_method= 'TRUNCATE')
