### ISSUE TITLE
Was this feature removed? cloudwatch to DataFrame - 

### ISSUE THREAD

**Issue by bodegus** [awslabs/aws-data-wrangler#241]
In pre-version 1 I was able to use this function to convert cloudwatch directly to a data frame. it now returns a nested list of field, value.

Is there a native pandas operation to convert this cleanly (using something like read_json)?   My current approach is to iterate twice (once per row, then once per key/value pair) which seems cumbersome?

```session.pandas.read_log_query(cloudwatch xargs) ->pd.DataFrame```

It looks like this has been replaced with 

```wr.cloudwatch.run_query -> [[{field, value}]] ```

example of how I am parsing this
```python
df = pd.DataFrame()
for row in result:
    s = pd.Series()
    for item in row:
        s[item['field']] = item['value']

    df = df.append(s, ignore_index=True)
```

**Comment by igorborgest** [comment]
Hi @bodegus, thanks for reaching out!

This feature stills in the library under a new signature ([`wr.cloudwatch.read_logs()`](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.cloudwatch.read_logs.html#awswrangler.cloudwatch.read_logs)) into the new CloudWatch module ([`wr.cloudwatch`](https://aws-data-wrangler.readthedocs.io/en/latest/api.html#cloudwatch-logs)).

The ([`wr.cloudwatch.run_query()`](https://aws-data-wrangler.readthedocs.io/en/latest/stubs/awswrangler.cloudwatch.run_query.html#awswrangler.cloudwatch.run_query)) function is just a alternative for those that want to receive the raw CloudWatch response instead of a Pandas DataFrame.

**Usage**:

```py3
import awswrangler as wr

df = wr.cloudwatch.read_logs(
    log_group_names=["..."],
    query="fields @timestamp, @message | sort @timestamp desc | limit 5"
)
```

Let us know any other question or suggestions!
