### ISSUE TITLE
Pinpointed version for SQLAlchemy dependency - is that intended?

### ISSUE THREAD

**Issue by zachmoshe** [awslabs/aws-data-wrangler#259]
The version of SQLAlchemy in requirements.txt is pinpointed to 1.3.13  (as opposed to "~=1.3.13").
This causes problems when depending on aws-data-wrangler together with other packages that only rely on "SQLAlchemy" (without a version specification), causing the project to have the latest SQLAlchemy (at the moment - 1.3.17).

Was that intentional or just a mistake?
I'd like to avoid pinpointing my dependency of SQLAlchemy as it will surely cause troubles going forward..

**Comment by igorborgest** [comment]
Hi @zachmoshe, thanks for reaching out!

It was intentional. We didn't dive deep on that **yet**, but seems that newer versions of SQLAlchemy does not install on Glue Python Shell environment (Even micro versions upgrades like `1.3.17`).

I will label this issue as an enhancement and start work on some possible solution for it.

**Comment by igorborgest** [comment]
After tests I can say that `sqlalchemy-redshift==0.7.*` is not compatible with `SQLAlchemy>=1.3.16`.

But I've adjusted the micro versions range to `SQLAlchemy>=1.3.10,<1.3.16` it will allow you to use a fresher SQLAlchemy (`1.3.15`) (see commit above).

**Comment by igorborgest** [comment]
Changes released on version [1.3.0](https://github.com/awslabs/aws-data-wrangler/releases/tag/1.3.0)

Thanks!
