### ISSUE TITLE
read_csv - pandas_kwargs argument 

### ISSUE THREAD

**Issue by armandwfourie** [awslabs/aws-data-wrangler#289]
**Describe the bug**
I want to use the `wr.s3.read_csv()` method to read csv files in s3.
When reading the files I want to specify the the dtype of the dataframe to be `str`.
However, when specifying the `dtype` under `pandas_kwargs` I get the following error:

`TypeError: parser_f() got an unexpected keyword argument 'pandas_kwargs'`

**Code**
Here is the code I am using:

`df = wr.s3.read_csv(
        path=object_key,
        pandas_kwargs={
            'dtype':str
        }
    )`

I am using awswrangler==1.5.0 and python version 3.7.7

**Comment by bryanyang0528** [comment]
@armandwfourie  I would not say that it is a bug. Because `pandas_kwargs` in `wr.s3.read_csv(path=path, **pandas_kwargs)` is a `keyworded argument`(https://book.pythontips.com/en/latest/args_and_kwargs.html) . So you can directly assign `dtype={'col': str}` in the function like:
```python
df = wr.s3.read_csv( path=object_key, dtype={'col': str})
```
And `dtype` should be a `dict` format. please the example from pandas official document below:  
```
dtypeType name or dict of column -> type, optional
Data type for data or columns. E.g. {‘a’: np.float64, ‘b’: np.int32, ‘c’: ‘Int64’} Use str or object together with suitable na_values settings to preserve and not interpret dtype. If converters are specified, they will be applied INSTEAD of dtype conversion.
```

Other pandas keywords and more detailed information you could find are in this document: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

**Comment by igorborgest** [comment]
Hi @armandwfourie, thanks for reach out to us!

@bryanyang0528 explained it perfectly 👍 

Please, let us know if it resolve your problem.

**Comment by armandwfourie** [comment]
Thanks for the quick response guys... Assumed that this would be referenced the same way as the s3_additional_kwargs.

This worked great thanks!

**Comment by igorborgest** [comment]
Hi @armandwfourie !

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
