### ISSUE TITLE
ImportError: Missing optional dependency 'fsspec'.  Use pip or conda to install fsspec.

### ISSUE THREAD

**Issue by tochandrashekhar** [awslabs/aws-data-wrangler#414]
Getting below error for version awswrangler-1.9.5-py3-none-any.whl
ImportError: Missing optional dependency 'fsspec'.  Use pip or conda to install fsspec.

Works fine for version awswrangler-1.6.3-py3-none-any.whl

**Comment by igorborgest** [comment]
Wrangler does not relies on `fsspec` anymore. You are probably facing some issue trying to access s3 directly through pandas without Wrangler. I highly recommend you to only access s3 through Wrangler function or install `s3fs/fsspec` by your self.

**Comment by tochandrashekhar** [comment]
I am reading excel file . As wrangler does not support excel , I am using pandas

**Comment by vfilimonov** [comment]
Hello @igorborgest 

What were the reasons to drop `s3fs` and `fsspec`? I see that now there's `s3transfer` as a dependency. I have not worked with it before - is it a successor for `s3fs`?

**Comment by igorborgest** [comment]
From #370

> Starting from version 5.0.0 s3fs depends of aiobotocore to use async requests. For Wrangler we've chose to keep relying on boto3/botocore directly (officially supported by AWS) with a multithreading approach for concurrent requests.

`s3transfer` is not a s3fs successor, it is a boto3 dependency and we don't rely on that directly.

This is our or built-in filesystem abstraction: https://github.com/awslabs/aws-data-wrangler/blob/master/awswrangler/s3/_fs.py

@vfilimonov 

- what is you use case?
- Will this filesystem abstraction be useful some way if we make it public?
- Why not just install s3fs by your self?

P.S. We already have a excel feature request #419

**Comment by vfilimonov** [comment]
Thanks for explanations @igorborgest. 
I'm not using `aws-data-wrangler`, but I saw that the dependency on `s3fs` was dropped and got curious - whether there is something with `s3fs` to be worried about.

My use case is straightforward - I use `s3fs.S3FileSystem` with `pyarrow.parquet.*_table` to read/write partitioned parquets. For other formats I use plain `boto3` functionality. When I was building my frameworks in January, `aws-data-wrangler` was in the early stage, so I chose the low level setup. There were some other requirements, that are specific to me:
- I needed on-the-fly gzip compression/decompression of other formats (CSV/JSON/PICKLE) within the same interface as reading uncompressed files
- Basic formats CSV/JSON/YAML should have been supported without pandas or other heavy dependency
- I needed interchangeability of protocols 's3://' with local 'file://' within the same interface
- Rather than having one big lambda layer with all packages, I decided to use multiple smaller layers, so that my lambda functions combine only those that are needed (the decision which looks not that great to me anymore)
- And also I ended up quite small with some rather plain partitioned structure, so Athena and SQL querying were not needed at the end

Now `aws-data-wrangler` which is much more mature - congratulations on the really great job! 
So I'm started to look at it again as there is a need for much bigger and less structured datasets.

**Comment by igorborgest** [comment]
> Do I understand correctly, that it is the version pinning of botocore by aiobotocore (dask/s3fs#357) that was the reason to drop it?

It is also a point, but it not only about that. It was a more general decision to avoid the dependency of this new intermediary layer of code and maintainers (aiobotocore). I really like s3fs and aiobotocore. I do believe this async adoption was the right choice for s3fs.

But thinking about the Wrangler context, it already relies on too much dependencies and in a big network of maintainers, so it is natural that we will try to mitigate that replacing some dependencies that have core functionalities and could be created internally without a massive work.

> My use case is straightforward - I use s3fs.S3FileSystem with pyarrow.parquet.*_table to read/write partitioned parquets. For other formats I use plain boto3 functionality. When I was building my frameworks in January, aws-data-wrangler was in the early stage, so I chose the low level setup. There were some other requirements, that are specific to me...

Yeah, makes sense to skip Wrangler and go to near the metal in your case. Wrangler does not has the mission to solve all scenarios. It is all about trade-off. Wrangler tries to save customer's time with some functions that will bundle sequences of commands/best practices but on the other hand it will eliminate some flexibility.
