### ISSUE TITLE
Input and output dataframes have different datatypes 

### ISSUE THREAD

**Issue by Natalie-Caruana** [awslabs/aws-data-wrangler#433]
Hi, I am trying to put the following dataframes to S3 buckets (in parquet format) and then reading data again from S3 to compare datatypes:
```
import awswrangler as wr
import boto3
import numpy as np
import pandas as pd
s3_client = boto3.client('s3')
l1 = np.array([['a'], [''], [None], ['c']])
l2 = np.random.random(size=(4, 2))
l = np.concatenate([l1,l2],axis=1)
dfx= pd.DataFrame(l, columns=['A', 'B', 'C'])
dfx.to_parquet('datax.parquet')
dfy = pd.DataFrame(np.random.random(size=(4,2)),columns=['A','B'])
dfy["C"] = pd.Series([1,2,3,4])
dfy.to_parquet('datay.parquet')
s3_client.upload_file(Bucket='bucketx',Key='datax.parquet',Filename='datax.parquet')
s3_client.upload_file(Bucket='buckety',Key='datay.parquet',Filename='datay.parquet')
list_of_paths = ['s3://bucketx/datax.parquet', 's3://buckety/datay.parquet']
gen_dfs = wr.s3.read_parquet(path=list_of_paths, chunked=True)
for df_in,df_out in zip([dfx,dfy],gen_dfs):
    print(df_in.dtypes)
    print(df_out.dtypes)
```
Output:
```
A    float64
B    float64
C      int64
dtype: object
A    float64
B    float64
C      Int64
dtype: object
A    float64
B    float64
C     object
dtype: object
A    float64
B    float64
C     string
dtype: object
```
Why are the df_in and df_out integer and string dtypes different?

**Comment by igorborgest** [comment]
AWS Data Wrangler is opinionated regarding data types, and tries to mitigates a lot of frequently faced issues when Pandas are used for load/unload process.

Wrangler always will try to use the "_latest version of each data type_" to make it more consistent and more compatible with the Parquet file format or database tables.

---

### E.g. 1
Text columns will always be handled as [string](https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html) type.
The object type has not directly representatives in the Parquet file format or database tables.
Also other points extracted from the Pandas official documentation:

> We recommend using StringDtype to store text data.
>
> Prior to pandas 1.0, object dtype was the only option. This was unfortunate for many reasons:
>    * You can accidentally store a mixture of strings and non-strings in an object dtype array. It’s better to have a dedicated dtype.
>    * object dtype breaks dtype-specific operations like DataFrame.select_dtypes(). There isn’t a clear way to select just text while excluding non-text but still object-dtype columns.
>    * When reading code, the contents of an object dtype array is less clear than 'string'.
>
> Currently, the performance of object dtype arrays of strings and arrays.StringArray are about the same. We expect future enhancements to significantly increase the performance and lower the memory overhead of StringArray.

### E.g. 2
Integer columns will always handled as [Int64](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html) type.
The regular `int64` type does not support null values. So there is no good reason to keep using this old type instead of the new `Int64`.

---

What do you think? Makes sense?

**Comment by Natalie-Caruana** [comment]
Hi, thanks for your reply and your explanation does make sense.  The only issue I see is that if you would need to copy the same dataframe (or same dataframe with added columns for example) to another bucket say, then you will have issues when running some tests to assert that the dataframes (or dataframes with common columns) are equal (unless you disable dtypes).  

You might have cases where you don't have control over the raw dataset (so you cannot change data types to conform with the data types of the output) and you need to make sure that what you copied matches the input.

**Comment by igorborgest** [comment]
Thanks for your thoughts @Natalie-Caruana.

I agree that would be better if we could have both at the same time (better data types and keep the same input types). But we made this choice to prioritize the best data types during the library design phase and now need to deal with the pros and cons.
