### ISSUE TITLE
GLUE SPARK - No module named 's3fs'

### ISSUE THREAD

**Issue by josecw** [awslabs/aws-data-wrangler#46]
Tried to run AWS Data Wrangler at Glue Spark but error is return No module named 's3fs'

**Comment by igorborgest** [comment]
Hi @BellyTheMagnificent, thanks for raise this point.

Unfortunately AWS Data Wrangler only supports Glue Python Shell jobs by now.
That's because Glue PySpark jobs doesn't support compiled (C/C++) dependencies like numpy.

As an option you can run AWS Data Wrangler on EMR. (P.S Don't forget to [setup Python3](https://aws.amazon.com/premiumsupport/knowledge-center/emr-pyspark-python-3x/))

I can see a good opportunity here to improve the documentation and make it more explicit! I will open a PR for that.

Btw, I will keep this issue open and blocked waiting for compiled dependencies support in the service.

**Comment by igorborgest** [comment]
Instructions on https://aws-data-wrangler.readthedocs.io/en/latest/install.html#aws-glue-pyspark-jobs

**Comment by igorborgest** [comment]
@josecw  

It is totally off-topic, but we are stating a [_"Who uses AWS Data Wrangler?"_](https://github.com/awslabs/aws-data-wrangler/tree/dev#who-uses-aws-data-wrangler) section. So feel free to add yourself if you want 😄 .
