### ISSUE TITLE
No module named 'redshift_connector'

### ISSUE THREAD

**Issue by jeyalee** [awslabs/aws-data-wrangler#475]
After upgrading to the latest version of AWS Wrangler, my lambda functions are failing with the following error:

```
{
  "errorMessage": "Unable to import module 'app': No module named 'redshift_connector'",
  "errorType": "Runtime.ImportModuleError"
}
```

I'm using the Sam CLI to build and deploy. My Python dependencies are bundled in a lambda layer. I do not experience the error in version 1.10.1

Versions:
SAM CLI 1.4.0
Python 3.8.6
AWS Wrangler 2.0.1

**Comment by igorborgest** [comment]
`redshift_connector` is a new dependency. You need to add it in your build, or just use our pre-built lambda Layer (you need to get layer version 2.0.1).

Take a look in our guide: https://aws-data-wrangler.readthedocs.io/en/stable/install.html#aws-lambda-layer

**Comment by laithalsaadoon** [comment]
Included it in my build, still getting the error. My requirements.txt file used in sam build --use-container with a 3.7 runtime:

```boto3
requests
aws-lambda-powertools
pandas
awswrangler
redshift_connector

**Comment by amolkokje** [comment]
I am still getting this error consistently. I tried using python3.7 and python3.8 runtime. 

```
{
  "errorMessage": "Unable to import module 'app': No module named 'redshift_connector'",
  "errorType": "Runtime.ImportModuleError"
}
```
My requirements.txt file is: 
```
awswrangler==2.3.0
beautifulsoup4==4.9.3
boto3==1.16.60
botocore==1.19.60
certifi==2020.12.5
chardet==4.0.0
et-xmlfile==1.0.1
idna==2.10
jdcal==1.4.1
jmespath==0.10.0
lxml==4.6.2
numpy==1.19.5
openpyxl==3.0.6
pandas==1.2.0
pg8000==1.16.6
pyarrow==2.0.0
PyMySQL==1.0.2
python-dateutil==2.8.1
pytz==2020.5
redshift-connector==2.0.873
requests==2.25.1
s3transfer==0.3.4
scramp==1.2.0
six==1.15.0
soupsieve==2.1
urllib3==1.26.3
```

With this requirements.txt file, my import command for redshift_connector works fine: 
```
(venv) akokje@akokje-mymachine s3-csv-to-parquet % python3.7
Python 3.7.5 (default, Oct 22 2019, 10:35:10) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import redshift_connector
>>> exit()
```

**Comment by 70nyIT** [comment]
Same here, with a configuration like the one of @amolkokje I'm getting the same error once lambda is deployed, and prevent me from executing it.

**Comment by igorborgest** [comment]
@amolkokje @70nyIT @laithalsaadoon 

AWS Data Wrangler has non-trivial dependencies to bundle and ship to AWS Lambda. We have compiled and big artifacts from libraries like Numpy, Pandas and PyArrow that must be optimized before bundled. So we don't recommend bundle these libraries within your Lambda code.

That's why the recommended and easier approach to use Wrangler on AWS Lambda is through our pre-built and optimized Lambda Layers. Take a look in our [step-by-step](https://aws-data-wrangler.readthedocs.io/en/stable/install.html#aws-lambda-layer). So you can keep using your current approach to bundle your other dependencies keeping Wrangler and friends in that dedicated layer.

If you really want to bundle the library by your own I recommend a look into the [script](https://github.com/awslabs/aws-data-wrangler/blob/main/building/lambda/build-lambda-layer.sh) we use to address that.

P.S. Besides AWS Data Wrangler, Lambda Layers are great. It can be versioned and shared among several distinct Lambdas Function keeping your Lambda bundles clean and light.

P.S.S. AWS recently released [AWS Lambda support for container images](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html). So it would also be a good approach. You just need to `pip install awswrangler` into your Dockerfile.

**Comment by igorborgest** [comment]
Reopen for discussion 🙂

**Comment by 70nyIT** [comment]
Thanks @igorborgest for your message, that helps a lot and I think makes everything more clear into this discussion. I'm sure more users will get into this situation. I will give definitively a try with Lambda Layers ;)

**Comment by amolkokje** [comment]
Thanks @igorborgest! I was able to get it work with Lambda Layer.
