### ISSUE TITLE
sanitize_dataframe_columns_names - support for excel datetime columns

### ISSUE THREAD

**Issue by nmduarteus** [awslabs/aws-data-wrangler#544]
**Problem:**

Using the `sanitize_dataframe_columns_names` in columns from an excel file will cause an error if the excel has the columns' as datetime instead of string.

`TypeError: normalize() argument 2 must be str, not datetime.datetime`

**Enhancement idea**

It might be interesting to cater for these cases now that awswrangler supports excel files - That way, the developer would not have to be worried about running checks/transformations in the columns' names before calling sanitize_dataframe_columns_names

**Comment by maxispeicher** [comment]
I'm not sure if the problem is really the Excel file or the way that the data is loaded. Are you sure that the column name itself is a datetime and you're not accidentally using actual data as the header row? I can't think of a good example right now, where the column name itself would be a datetime.
Just as an example if you have an Excel file like:
```
0 datetime
1 2021-02-03
2 2021-02-04
3 2021-02-08
```
everything should work fine.

However if the file looks like:
```
0 2021-02-03
1 2021-02-04
2 2021-02-08
```
you need to pass `names=["datetime"]` and `header=None` as pandas kwargs.

If your problem is not related to what I've tried to describe, I'm happy to provide a fix, but I just want to make sure what exactly the problem is 🙂.

**Comment by nmduarteus** [comment]
Hi @maxispeicher ,

sorry to take so long to come back to you. Just tried again the same file and seems to be working fine ?! The headers are indeed in a custom format (datetime) - the headers represent each month, so this wasn't data itself, but the actual headers.

I might be crazy here, but I am pretty sure that I am testing the same file...

well, better this way :)

thanks for taking the time - i will close it.
