### ISSUE TITLE
Use data wrangler package in AWS Lambda exceed maximum size 262144000 bytes

### ISSUE THREAD

**Issue by qingfei1994** [awslabs/aws-data-wrangler#575]
I tried to use data wrangler in AWS Lambda function as a dependency, but the package is too large to import(about 259M)
And we got below error. 
`botocore.errorfactory.InvalidParameterValueException:An error occurred(InvalidParameterValueException) when calling the PublishLayerVersion operation: Unzipped size must be smaller than 262144000 bytes`

Do we expect the data wrangler to be used as a dependency in Lambda? If so, how to use it?

**Comment by maxispeicher** [comment]
You can use the provided Lambda Layer for using `awswrangler` inside of Lambda functions. 
Instructions for it can be found in the Install documentation: https://aws-data-wrangler.readthedocs.io/en/2.4.0-docs/install.html#aws-lambda-layer

**Comment by mdavis-xyz** [comment]
I would prefer not to use a lambda layer, because that involves changing my tooling for deployment and unit testing.

What about if I write a PR to install this library like [moto](https://github.com/spulec/moto#install).

i.e. `pip install awswrangler` installs everything, but if I do `pip install awswrangler[athena]` that will only install the components required for connecting to Athena (i.e. no pyodbc, no openpyxl etc)?

**Comment by maxispeicher** [comment]
The problem is that the `extras` feature in python only supports extending the required packages. This means that it is not possible that `pip install awswrangler[athena]` installs less than `pip install awswrangler` as it would always install all packages which are required by `awswrangler`.
