### ISSUE TITLE
[ERROR] ValueError: invalid literal for int() with base 10: '21.'

### ISSUE THREAD

**Issue by jeyalee** [awslabs/aws-data-wrangler#658]
I'm trying to write a parquet file to S3 using `wr.s3.to_parquet` and I'm setting the dtype for a column as int `{"NUMERICAL_OPERATIONS_NUMBER": "int"}`, but the operation is failing and returning a value error `[ERROR] ValueError: invalid literal for int() with base 10: '21.'` There is a decimal after 21 so it's failing, but I'm not sure why the decimal is being placed there when I am setting the dtype as int. Please help.

**Comment by maxispeicher** [comment]
My guess would be that the original `df` has `object` as the column datatype and the values simply as strings. What happens internally in `awswrangler` when specifying `dtype` is something like `df["NUMERICAL_OPERATIONS_NUMBER"] = df["NUMERICAL_OPERATIONS_NUMBER"].astype(int)`, which fails for a string like `"21."`.
One way to "fix" this issue is for example that you manually cast the column to float beforehand but there are other ways aswell.
```python
df["NUMERICAL_OPERATIONS_NUMBER"] = df["NUMERICAL_OPERATIONS_NUMBER"].astype(float)
wr.s3.to_parquet(df, ..., dtype={"NUMERICAL_OPERATIONS_NUMBER": "int"})
```
