### ISSUE TITLE
Problems connecting to AWS RDS Proxy with pg8000

### ISSUE THREAD

**Issue by tlocke** [awslabs/aws-data-wrangler#770]
Hello AWS, maintainer of pg8000 here. I'm receiving a trickle of reports of people unable to connect to AWS RDS proxy with pg8000. There's a Stack Overflow question on it:

https://stackoverflow.com/questions/67242059/aws-rds-proxy-error-postgres-rds-proxy-currently-doesn-t-support-command-lin

and it's also discussed in a pull request for pg8000:

https://github.com/tlocke/pg8000/pull/72

I don't have access to AWS, so any help you're able to give is gratefully received.

**Comment by kukushking** [comment]
Thanks for getting in touch - I'll have a look.

**Comment by kukushking** [comment]
Hey Tom, I couldn't replicate the issue neither with 1.19.4 not 1.19.5 - both work all right in my setup (PostgreSQL 12.5, TLS-enforcing proxy, running from AWS Lambda in the same VPC as the database & proxy). Looking briefly at stackoverflow a few very common issues seem to be due to the following [limitations](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html#rds-proxy.limitations):
>You can't use RDS Proxy with Aurora Serverless clusters.

>Your RDS Proxy must be in the same VPC as the database. The proxy can't be publicly accessible, although the database can be.

Regarding the 1.19.4 patch not working - something else must have changed in the client setup. If I have to guess I'd say it was misconfiguration of VPC security group (missing IP of the client).

I will close this for now as it appears to work, as well as it's not related to AWS Data Wrangler.

**Comment by tlocke** [comment]
Cool, thanks for checking it out @kukushking
