### ISSUE TITLE
Update function create_csv_table, create_parquet_table to register exciting datasets to Glue catalog, without manually input colume DDL

### ISSUE THREAD

**Issue by samliuq** [awslabs/aws-data-wrangler#786]
**Is your idea related to a problem? Please describe.**
Current function to_csv and to_parquet are very helpful, but it combine the data write and table registration.
Create_csv_table, create_parquet_table request user to input all table column DDL in dtype.

It will be very helpful if we can have an API that register data existing in s3 to glue catalog, without requesting dtype. Combining the goodness of the two group.

eg. wr.catalog.create_csv_table(path = "s3://sdsd/sds")
 
**Describe the solution you'd like**

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by jaidisido** [comment]
A combination of [wr.s3.read_parquet_metadata](https://aws-data-wrangler.readthedocs.io/en/stable/stubs/awswrangler.s3.read_parquet_metadata.html#awswrangler.s3.read_parquet_metadata) and `wr.catalog.create_parquet_table` should enable to do that. The first method infers columns, partitions and their types from the parquet files metadata. The result can then be fed to the second method. This is less relevant for CSV since all data is stored as String in the files.
