### ISSUE TITLE
CI/CD File Permissions (Container ID 165636 cannot be mapped to a host ID)

### ISSUE THREAD

**Issue by PvanHengel** [awslabs/aws-data-wrangler#803]
Hi,

I've narrowed down our bitbucket build failures to this package, and hope someone can help fix.  It seems there may be a file permissions issue somewhere / ownership that causes cloud based builds to fail with the error:

`Error processing tar file(exit status 1): Container ID 165636 cannot be mapped to a host ID`

Sample docker file to repliace on BitBucket Cloud

```
FROM jupyter/scipy-notebook
RUN python -m pip install awswrangler
``` 

I have found some articles such as:
https://circleci.com/docs/2.0/high-uid-error/
https://jira.atlassian.com/browse/BCLOUD-17319?focusedCommentId=2654226&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&error=login_required&error_description=Login+required&state=ab5a6f15-04fa-4215-9184-c7f2f159b460

but to no avail... Anyone else experiencing issues with cloud builds?

Thanks,
Peter

**Comment by kukushking** [comment]
Hi @PvanHengel when you say you narrowed it down do you mean removing `RUN python -m pip install awswrangler` fixes the build?

**Comment by PvanHengel** [comment]
@kukushking no, that line breaks the build,  I had a lot of other stuff in the build that I removed to be sure. That is the line where it breaks.  

I continued to debug, and interesting I can install all the packages manually in separate layers from the requirements.txt file, they all work, until the last one, which is the wranger package that breaks it (last line)

```
FROM jupyter/scipy-notebook

RUN python -m pip install boto3
RUN python -m pip install botocore
RUN python -m pip install numpy
RUN python -m pip install pandas
RUN python -m pip install pyarrow
RUN python -m pip install redshift-connector
RUN python -m pip install pymysql
RUN python -m pip install pg8000
RUN python -m pip install openpyxl

RUN python -m pip install awswrangler==2.8.0
```

**Comment by kukushking** [comment]
@PvanHengel  Seems to be [userns-remap](https://docs.docker.com/engine/security/userns-remap/) that is breaking the image. Here's also an article [from Atlassian](https://community.atlassian.com/t5/Bitbucket-articles/Changes-to-make-your-containers-more-secure-on-Bitbucket/ba-p/998464) (point 2) that is describing the issue & the fix. 

Jupyter images provide fix-permissions helper script so as a fix you can run it after you install to fix the ownership:

```
FROM jupyter/scipy-notebook
USER $NB_UID
RUN conda install awswrangler  && \
    fix-permissions "${CONDA_DIR}"
```
Note I'm using conda because that's what base image is using, but pip should work just as fine.

Feel free to reopen if it doesn't help
