### ISSUE TITLE
Stop pinning the minor version of pandas

### ISSUE THREAD

**Issue by impredicative** [awslabs/aws-data-wrangler#805]
In v2.9.0, `awswrangler` pins pandas to <1.3.0. Recently, this was [updated to <1.4.0](https://github.com/awslabs/aws-data-wrangler/commit/c77848a0246fbd6534777bacc0ac0d3b04765144#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552), but this change hasn't been released yet. This is stopping me from using v1.3.0 of pandas. It is disruptive. Why not just pin pandas to <2.0.0 instead?

**Comment by jaidisido** [comment]
Hi @impredicative,

A few things here. First, pandas 1.3.0 is currently the [latest](https://pypi.org/project/pandas/) version of the library. 1.4.0 is in [dev](https://pandas.pydata.org/pandas-docs/dev/). But to your question, the reason why we pin some libraries to minor is to control potential breaking changes from upgrades between our releases. AWS Data Wrangler releases go through rigorous testing against specific versions of not only Python libraries but also Python versions. If we pin to major we cannot vouch for and test dependency upgrades that were released between our own releases. So if say pandas==1.4.0 has a major bug, then wrangler users would be impacted too and we would either have to wait for a fix from pandas or downgrade our requirements through a hot fix. None is ideal.

That being said, while we try to stay in sync with the latest dependencies versions, nothing is keeping users from overriding them if they wish. To do so, in your Python virtual environment, you can create a `constraints.txt` file with the library version you wish to override (e.g. overriding pandas from 1.1.0 to 1.3.0 in awswrangler 2.3.0).

File would look like:
```
pandas==1.3.0
```
then running:
```
pip install -c constraints.txt awswrangler==2.3.0
```
would force a pandas 1.3.0 installation instead of 1.1.0.

**Comment by impredicative** [comment]
If pandas breaks its backward compatibility in a minor release, then you're not expected to vouch for it working. Pandas is not expected to break backward compatibility in a minor release, and if they do, it's their fault.

It is a general expectation that if a maximum version is pinned in a package, only the major version is pinned as such, e.g. <2.0.0.

**Comment by jaidisido** [comment]
I understand your view however while it might be their fault we are ultimately responsible for the library and it has happened too often that we needed to push a fix so we prefer to limit the scope of changes release.
