### ISSUE TITLE
How to avoid printing " WARNING - urllib3.connectionpool -   Connection pool is full, discarding connection: some-s3-bucket.s3.amazonaws.com"?

### ISSUE THREAD

**Issue by zhiqiangdon** [awslabs/aws-data-wrangler#821]
In my distributed training of deep models, each worker iterates a generator created by the awswrangler.s3.read_parquet(). I find that the console keeps printing the annoying message "WARNING - urllib3.connectionpool -   Connection pool is full, discarding connection: some-s3-bucket.s3.amazonaws.com". I have tried two ways to avoid the printing.

1. Setting use_threads=50
`df_iter = awswrangler.s3.read_parquet(path=part_file_list, chunked=chunked, use_threads=50)`

2. Using a customized boto3 session
`s3_session = boto3.session.Session()`
`s3_session.client('s3', config=botocore.config.Config(max_pool_connections=50))`
`df_iter = awswrangler.s3.read_parquet(path=file_list, chunksize=chunked, boto3_session=s3_session)`

However, both of them cannot stop it from printing the warning message. Can anyone provide some example code to fix this?

Thanks,

**Comment by jaidisido** [comment]
Hi - these seem to be `urllib3` specific warning messages. According to their docs, you should be able to just [suppress](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings) them.

**Comment by zhiqiangdon** [comment]
Thanks, @jaidisido 

Suppressing them works.

**Comment by gm42** [comment]
`urllib3.disable_warnings()` works only for the TLS warnings, it will not suppress the "Connection pool is full" warning; there is no way to suppress those, short of intercepting the log warning messages.

**Comment by starrlingo** [comment]
Try this
```
import logging
logging.getLogger("urllib3.connectionpool").setLevel(logging.ERROR)
```

**Comment by tuliocasagrande** [comment]
Hey team, I'm facing the same issue, but I don't believe the warning message (or suppressing them) is really my concern. I'd prefer to really increase the pool size to better utilize my node processing power and potentially speeding up my loading time.

The problem as I see is that OP's snippet had a mistake, since calling `s3_session.client` simply returns a `client` object and does not modify the original `session` object. In other words, the following line is doing nothing:
```
s3_session.client('s3', config=botocore.config.Config(max_pool_connections=50))
```

However, `wr.s3.read_parquet` only exposes `boto3_session` as a parameter and we don't have an equivalent `s3_client`.
Instead, it seems `s3_client` is internally created here: https://github.com/aws/aws-sdk-pandas/blob/da4ba40cd5bcdcb32b1e3ff370cf2e6eac8df4a0/awswrangler/s3/_read_parquet.py#L497

So that's the place we could override the default `max_pool_connections` from botocore. Here's an idea re-using the `use_threads` parameter in the case it's an integer (something different would need to be done in case `use_threads=True`):
```
s3_client = _utils.client(service_name="s3", session=boto3_session, config=botocore.config.Config(max_pool_connections=use_threads))
```

Alternatively, it seems to me that `botocore.config` is being set here and this could be another way that we could increase the pool size:
https://github.com/aws/aws-sdk-pandas/blob/da4ba40cd5bcdcb32b1e3ff370cf2e6eac8df4a0/awswrangler/_utils.py#L236-L249

Maybe increasing urllib3's pool size would change much, but I believe it's worth trying.
