### ISSUE TITLE
AttributeError: module 'awswrangler' has no attribute 'pandas'

### ISSUE THREAD

**Issue by RandomTreesAI** [awslabs/aws-data-wrangler#87]
When trying to read CSV from s3, am getting below error:-

**AttributeError: module 'awswrangler' has no attribute 'pandas'**

Please let me know how to resolve it.

**Comment by igorborgest** [comment]
Hi @RandomTreesAI,
Which version are you running?

**Comment by igorborgest** [comment]
AWS Data Wrangler using the Default Session is only allowed after version 0.1.3.

**Comment by mksadoughi** [comment]
Hello I have had the same problem. I believe this is due to the update in awswrangler module. 
For example for querying data using Athena I could run the following line without any problem: 
$ data = wr.pandas.read_sql_athena(sql = sql_query, database="db-name")

But now I would get the following error: 
 ---   AttributeError: module 'awswrangler' has no attribute 'pandas'.  ----


For solving this issue, just look into this newly released doc for updated version of awswrangler: 
https://readthedocs.org/projects/aws-data-wrangler/downloads/pdf/latest/
Use the following code for querying data which works now: 
$ data = wr.athena.read_sql_query(sql = sql_query, database="db-name")
