### ISSUE TITLE
Is it possible to use pymssql instead of pyodbc for Sql server Integration?

### ISSUE THREAD

**Issue by kkyon** [awslabs/aws-data-wrangler#910]
**Is your feature request related to a problem? Please describe.**
 it is impossible to install  pyodbc in glue python job. Glue can use prebuilt pymssql   library. 

**Describe the solution you'd like**
 Is it possible use pymssql instead of pyodbc for Sql server Integration?

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by kukushking** [comment]
`pymssql` implements DB-API 2.0 so yes it should be possible to swap one for the other fairly easily.  We'll research consider it for the next release.

**Comment by maxispeicher** [comment]
It was at first implemented based on `pymssql`. However, it was swapped for `pyodbc` because of the reasons here: https://github.com/awslabs/aws-data-wrangler/pull/498#pullrequestreview-560634679

If these are still valid points, might be evaluated again. But back in the time the decision went towards `pyodbc`.

**Comment by mauro-mascia** [comment]
@maxispeicher I think that @kkyon comment was a valid point. It seems to be impossible to install pyodbc in glue python job.

**Comment by EchedelleLR** [comment]
This is currently being a Python Shell limit which does not happen with neither MySQL/MariaDB nor PostgreSQL.
